# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, content, public ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    
    - name: "Checkout Content"
      uses: actions/checkout@v3
      with:
        ref: content
        path: content

    - name: "Checkout Media (public folder)"
      uses: actions/checkout@v3
      with:
        ref: public
        path: public

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: yarn install --immutable
    - run: yarn run build
    - run: yarn run export
    - run: touch ./out/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: out
